# villa = ویلاها. Record-only NVR.
mqtt:
  enabled: false

auth:
  cookie_secure: false
  session_length: 2592000
  refresh_time: 1296000

detect:
  enabled: false

record:
  enabled: true
  retain:
    days: 1
    mode: all

snapshots:
  enabled: false

birdseye:
  enabled: false

ffmpeg:
  global_args: -hide_banner -loglevel warning
  output_args:
    record: preset-record-generic

go2rtc:
  streams:
    villa_ha:
      - rtsp://admin:1259110%40av@192.168.51.51:554/Streaming/Channels/102
    villa_ha_gharb:
      - rtsp://admin:admin123@192.168.51.12:554/Streaming/Channels/102
    cam_20:
      - rtsp://admin:admin123@192.168.51.20:554/Streaming/Channels/102
    cam_43:
      - rtsp://admin:admin123@192.168.51.43:554/Streaming/Channels/102
    cam_44:
      - rtsp://admin:admin123@192.168.51.44:554/Streaming/Channels/102

cameras:
  villa_ha:
    ffmpeg: { inputs: [{ path: rtsp://127.0.0.1:8554/villa_ha, input_args: preset-rtsp-restream, roles: [record] }] }
  villa_ha_gharb:
    ffmpeg: { inputs: [{ path: rtsp://127.0.0.1:8554/villa_ha_gharb, input_args: preset-rtsp-restream, roles: [record] }] }
  cam_20:
    ffmpeg: { inputs: [{ path: rtsp://127.0.0.1:8554/cam_20, input_args: preset-rtsp-restream, roles: [record] }] }
  cam_43:
    ffmpeg: { inputs: [{ path: rtsp://127.0.0.1:8554/cam_43, input_args: preset-rtsp-restream, roles: [record] }] }
  cam_44:
    ffmpeg: { inputs: [{ path: rtsp://127.0.0.1:8554/cam_44, input_args: preset-rtsp-restream, roles: [record] }] }

version: 0.16-0
