/** Site definitions — keep in sync with docs/CAMERAS.md */
const SITES = [
  {
    id: "cafe",
    slug: "cafe",
    title: "کافه",
    titleEn: "Cafe",
    description: "DVR کافه و دوربین‌های IP بخش کافه",
    icon: "☕",
    port: 8972,
    cameraCount: 10,
    enabled: true,
    healthPath: "/health/cafe/",
    apiPath: "/cafe/api/",
    cssClass: "card--active",
  },
  {
    id: "center11",
    slug: "center11",
    title: "پذیرش و ورودی مجتمع",
    titleEn: "Reception & Complex Entrance",
    description: "دوربین‌های پذیرش، ورودی مجتمع و اتاق سرور",
    icon: "🏨",
    port: 8973,
    cameraCount: 8,
    enabled: true,
    healthPath: "/health/center11/",
    apiPath: "/center11/api/",
    cssClass: "card--active",
  },
  {
    id: "restaurant",
    slug: "restaurant",
    title: "رستوران",
    titleEn: "Restaurant",
    description: "رستوران، آشپزخانه و سردخانه",
    icon: "🍽️",
    port: 8975,
    cameraCount: 7,
    enabled: true,
    healthPath: "/health/restaurant/",
    apiPath: "/restaurant/api/",
    cssClass: "card--active",
  },
  {
    id: "sahel",
    slug: "sahel",
    title: "ساحل",
    titleEn: "Beach",
    description: "دوربین‌های ساحل شرق و غرب",
    icon: "🏖️",
    port: 8976,
    cameraCount: 4,
    enabled: true,
    healthPath: "/health/sahel/",
    apiPath: "/sahel/api/",
    cssClass: "card--active",
  },
  {
    id: "villa",
    slug: "villa",
    title: "ویلاها",
    titleEn: "Villas",
    description: "دوربین‌های ویلاها و جلوی ارکیده",
    icon: "🏠",
    port: 8977,
    cameraCount: 5,
    enabled: true,
    healthPath: "/health/villa/",
    apiPath: "/villa/api/",
    cssClass: "card--active",
  },
  {
    id: "mahoote",
    slug: "mahoote",
    title: "محوطه",
    titleEn: "Grounds",
    description: "محوطه، ژنراتور، دیوار شرقی و بالای رستوران",
    icon: "🌳",
    port: 8978,
    cameraCount: 13,
    enabled: true,
    healthPath: "/health/mahoote/",
    apiPath: "/mahoote/api/",
    cssClass: "card--active",
  },
  {
    id: "center22",
    slug: "center22",
    title: "پارکینگ",
    titleEn: "Parking",
    description: "پارکینگ‌های ۱ تا ۴ و موتورخانه پارکینگ ۱",
    icon: "🅿️",
    port: 8974,
    cameraCount: 16,
    enabled: true,
    healthPath: "/health/center22/",
    apiPath: "/center22/api/",
    cssClass: "card--active",
  },
  {
    id: "tasisat",
    slug: "tasisat",
    title: "تاسیسات",
    titleEn: "Facilities",
    description: "دیوار غربی؛ تصفیه‌خانه فاضلاب و پشت لاله (cam_61 تا cam_65)",
    icon: "⚙️",
    port: 8980,
    cameraCount: 5,
    enabled: true,
    authDisabled: true, // از پورت 5000 بدون لاگین سرو می‌شود
    healthPath: "/health/tasisat/",
    apiPath: "/tasisat/api/",
    cssClass: "card--active",
  },
  {
    id: "entezamat",
    slug: "entezamat",
    title: "انتظامات",
    titleEn: "Security",
    description: "دوربین‌های انتظامات و کانکس ساحل",
    icon: "🛡️",
    port: 8981,
    cameraCount: 3,
    enabled: true,
    authDisabled: true, // از پورت 5000 بدون لاگین سرو می‌شود
    healthPath: "/health/entezamat/",
    apiPath: "/entezamat/api/",
    cssClass: "card--active",
  },
  {
    id: "anbar",
    slug: "anbar",
    title: "انبار",
    titleEn: "Warehouse",
    description: "انبار مرکزی و خانه‌داری (DVR) + cam_97",
    icon: "📦",
    port: 8982,
    cameraCount: 3,
    enabled: true,
    authDisabled: true, // از پورت 5000 بدون لاگین سرو می‌شود
    healthPath: "/health/anbar/",
    apiPath: "/anbar/api/",
    cssClass: "card--active",
  },
  {
    // موقت — دوربین‌های باقی‌مانده برای بررسی. بعد از تعیین تکلیف حذف شود.
    id: "temp",
    slug: "temp",
    title: "موقت — بررسی دوربین‌ها",
    titleEn: "Temporary — Review",
    description: "۱۰ دوربین برای بررسی (بدون تصویر + برگردانده‌شده + خانه‌داری)",
    icon: "🧪",
    port: 8979,
    cameraCount: 10,
    enabled: true,
    temporary: true,
    authDisabled: true, // از پورت 5000 بدون لاگین سرو می‌شود
    healthPath: "/health/temp/",
    apiPath: "/temp/api/",
    cssClass: "card--active",
  },
];

/**
 * Inventory overview (docs/CAMERAS.md).
 * total = همه دوربین‌های شناخته‌شده
 * inactive = هنوز فعال نشده / planned
 * broken = قبلاً فعال بوده یا باید فعال باشد ولی الان قطع است
 */
const CAMERA_INVENTORY = {
  // active=74 در نمونه‌های دائمی + temp=10 (در حال بررسی) + ch10 planned=1
  total: 85,
  inactive: 11, // 10 در نمونه موقت temp + dvr_cafe_ch10
  broken: 0, // در حال بررسی در نمونه temp
};
