/** Site definitions — keep in sync with docs/CAMERAS.md */
const SITES = [
  {
    id: "cafe",
    slug: "cafe",
    title: "کافه",
    titleEn: "Cafe",
    description: "DVR کافه و دوربین‌های IP بخش کافه",
    icon: "☕",
    port: 8972,
    cameraCount: 10,
    enabled: true,
    healthPath: "/health/cafe/",
    apiPath: "/cafe/api/",
    cssClass: "card--active",
  },
  {
    id: "center11",
    slug: "center11",
    title: "پذیرش و ورودی مجتمع",
    titleEn: "Reception & Complex Entrance",
    description: "دوربین‌های پذیرش و ورودی مجتمع",
    icon: "🏨",
    port: 8973,
    cameraCount: 7,
    enabled: true,
    healthPath: "/health/center11/",
    apiPath: "/center11/api/",
    cssClass: "card--active",
  },
  {
    id: "restaurant",
    slug: "restaurant",
    title: "رستوران",
    titleEn: "Restaurant",
    description: "دوربین‌های رستوران (بالا، پایین، صندوق و ...)",
    icon: "🍽️",
    port: 8975,
    cameraCount: 7,
    enabled: true,
    healthPath: "/health/restaurant/",
    apiPath: "/restaurant/api/",
    cssClass: "card--active",
  },
  {
    id: "sahel",
    slug: "sahel",
    title: "ساحل",
    titleEn: "Beach",
    description: "دوربین‌های ساحل شرق و غرب",
    icon: "🏖️",
    port: 8976,
    cameraCount: 5,
    enabled: true,
    healthPath: "/health/sahel/",
    apiPath: "/sahel/api/",
    cssClass: "card--active",
  },
  {
    id: "villa",
    slug: "villa",
    title: "ویلاها",
    titleEn: "Villas",
    description: "دوربین‌های ویلاها",
    icon: "🏠",
    port: 8977,
    cameraCount: 7,
    enabled: true,
    healthPath: "/health/villa/",
    apiPath: "/villa/api/",
    cssClass: "card--active",
  },
  {
    id: "mahoote",
    slug: "mahoote",
    title: "محوطه",
    titleEn: "Grounds",
    description: "دوربین‌های محوطه (ژنراتور و ...)",
    icon: "🌳",
    port: 8978,
    cameraCount: 13,
    enabled: true,
    healthPath: "/health/mahoote/",
    apiPath: "/mahoote/api/",
    cssClass: "card--active",
  },
  {
    id: "center22",
    slug: "center22",
    title: "پارکینگ",
    titleEn: "Parking",
    description: "دوربین‌های پارکینگ و انبار",
    icon: "🅿️",
    port: 8974,
    cameraCount: 12,
    enabled: true,
    healthPath: "/health/center22/",
    apiPath: "/center22/api/",
    cssClass: "card--active",
  },
  {
    id: "tasisat",
    slug: "tasisat",
    title: "تاسیسات",
    titleEn: "Facilities",
    description: "تسویه‌خانه (cam_81، cam_83) و خشکشویی (cam_95)",
    icon: "⚙️",
    port: 8980,
    cameraCount: 3,
    enabled: true,
    healthPath: "/health/tasisat/",
    apiPath: "/tasisat/api/",
    cssClass: "card--active",
  },
  {
    id: "entezamat",
    slug: "entezamat",
    title: "انتظامات",
    titleEn: "Security",
    description: "دوربین‌های انتظامات",
    icon: "🛡️",
    port: 8981,
    cameraCount: 2,
    enabled: true,
    healthPath: "/health/entezamat/",
    apiPath: "/entezamat/api/",
    cssClass: "card--active",
  },
  {
    // موقت — دوربین‌های باقی‌مانده برای بررسی. بعد از تعیین تکلیف حذف شود.
    id: "temp",
    slug: "temp",
    title: "موقت — بررسی دوربین‌ها",
    titleEn: "Temporary — Review",
    description: "۶ دوربین باقی‌مانده (۴ بدون تصویر + cam_82، cam_112 بدون مقصد)",
    icon: "🧪",
    port: 8979,
    cameraCount: 6,
    enabled: true,
    temporary: true,
    healthPath: "/health/temp/",
    apiPath: "/temp/api/",
    cssClass: "card--active",
  },
];

/**
 * Inventory overview (docs/CAMERAS.md).
 * total = همه دوربین‌های شناخته‌شده
 * inactive = هنوز فعال نشده / planned
 * broken = قبلاً فعال بوده یا باید فعال باشد ولی الان قطع است (فقط cam_16 —
 *          cam_14 با نام restoran_sandogh در نمونه restaurant فعال شد)
 */
const CAMERA_INVENTORY = {
  // active=66 در نمونه‌های دائمی + temp=6 (در حال بررسی) + ch10 planned=1
  total: 73,
  inactive: 7, // 6 در نمونه موقت temp + dvr_cafe_ch10
  broken: 0, // خراب‌ها حذف شدند
};
