# tasisat = تاسیسات. در انتظار نصب ۱۲ دوربین جدید پارکینگ ۱.
# cam_85 (اتاق تاسیسات) از temp منتقل و فعال شد.
mqtt:
  enabled: false

auth:
  cookie_secure: false
  session_length: 2592000
  refresh_time: 1296000

detect:
  enabled: false
  fps: 3

record:
  enabled: true
  retain:
    days: 1
    mode: all

snapshots:
  enabled: false

birdseye:
  enabled: false

ffmpeg:
  global_args: -hide_banner -loglevel warning
  output_args:
    record: preset-record-generic

go2rtc:
  streams:
    cam_85:
      - rtsp://admin:admin123@192.168.51.85:554/Streaming/Channels/102

cameras:
  cam_85:
    ffmpeg: { inputs: [{ path: rtsp://127.0.0.1:8554/cam_85, input_args: preset-rtsp-restream, roles: [record] }] }

version: 0.16-0
